[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
solana_todo_app = "GSdLaosgZz3jkC3Jou5hNwEBZY5ZLBf6z16UdbRL6NqQ"

[programs.devnet]
solana_todo_app = "GSdLaosgZz3jkC3Jou5hNwEBZY5ZLBf6z16UdbRL6NqQ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
